import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import SiennaWidget from "../components/accessibility/SiennaWidget.js";
import Header from "@/components/Header/Header";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${roboto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <main className="mt-12">{children}</main>
        <SiennaWidget />
      </body>
    </html>
  );
}
